name: Test Encryption Scripts

on:
  push:
    branches: [ master, main ]
    paths:
      - 'encrypt.ps1'
      - 'decrypt.ps1'
      - '.github/workflows/test-encryption.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'encrypt.ps1'
      - 'decrypt.ps1'
      - '.github/workflows/test-encryption.yml'
  workflow_dispatch:

jobs:
  test-encryption:
    runs-on: windows-latest
    
    env:
      ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
      ENCRYPTION_SALT: ${{ secrets.ENCRYPTION_SALT }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test encryption with environment variables
      shell: pwsh
      env:
        TEST_SECRET: ${{ secrets.OCTOPUS_DB_USERNAME }}
      run: |
        Write-Host "Testing encryption/decryption with environment variables..." -ForegroundColor Cyan
        
        $testSecret = $env:TEST_SECRET
        if ([string]::IsNullOrWhiteSpace($testSecret)) {
            Write-Host "⚠️ OCTOPUS_DB_USERNAME secret not found, using fallback test value" -ForegroundColor Yellow
            $testSecret = "MyTestSecret123!@#"
        }
        
        Write-Host "Original secret: [length=$($testSecret.Length)]" -ForegroundColor Yellow
        
        # Encrypt using environment variables
        $encrypted = & .\encrypt.ps1 -SecretValue $testSecret
        Write-Host "Encrypted: $encrypted" -ForegroundColor Green
    
    - name: Test encryption with explicit parameters
      shell: pwsh
      run: |
        Write-Host "`nTesting encryption/decryption with explicit parameters..." -ForegroundColor Cyan
        
        $testSecret = "AnotherTestSecret456$%^"
        $password = $env:ENCRYPTION_PASSWORD
        $salt = $env:ENCRYPTION_SALT
        
        Write-Host "Original secret: $testSecret" -ForegroundColor Yellow
        
        # Encrypt with explicit parameters
        $encrypted = & .\encrypt.ps1 -SecretValue $testSecret -Password $password -SaltString $salt
        Write-Host "Encrypted: $encrypted" -ForegroundColor Green

    
    - name: Encrypt OCTO_RBXD_API_KEY
      shell: pwsh
      env:
        API_KEY: ${{ secrets.OCTO_RBXD_API_KEY }}
      run: |
        Write-Host "`n🔐 Encrypting OCTO_RBXD_API_KEY..." -ForegroundColor Cyan
        Write-Host "=" * 50 -ForegroundColor Cyan
        
        if ([string]::IsNullOrWhiteSpace($env:API_KEY)) {
            Write-Host "⚠️ OCTO_RBXD_API_KEY secret not found - skipping" -ForegroundColor Yellow
            exit 0
        }
        
        Write-Host "API Key length: $($env:API_KEY.Length)" -ForegroundColor Yellow
        
        # Encrypt the API key
        $encrypted = & .\encrypt.ps1 -SecretValue $env:API_KEY
        
        Write-Host "`n✅ Encrypted OCTO_RBXD_API_KEY:" -ForegroundColor Green
        Write-Host $encrypted -ForegroundColor White
        Write-Host "`n💡 Save this encrypted value to use in your workflows!" -ForegroundColor Cyan
        Write-Host "=" * 50 -ForegroundColor Cyan
